#!/bin/bash

path_run=$(dirname $0)

. $path_run/inc/api.sh
. $path_run/inc/filters.sh
. $path_run/inc/out.sh
. $path_run/inc/error.sh

if [ $# -eq 0 ]; then
	error_pros 1
fi

pattern=$path_run/parse/${@:$#}

if [ ! -e $pattern ]; then
	error_pros 2
fi

declare -a group
declare -a blocks
fl=0
nest=0
name_gr=" "
path=""
str=""
rn=""
limit=0
cx=0

init_pattern $pattern
init_format
type="bb_conf_${@:$#}"
line=""
i=$?

if [ $i -ne 0 ]; then
	let "i=$i+3"
	error_pros $i
fi

while getopts ":n:r:t:k:lfqeswz:" opt
do
	parm=${OPTARG// /@}
	case $opt in
		r) str="$str filter_nest@$parm";;
		n) str="$str filter_name@$parm";;
		t) str="$str filter_type@$parm";;
		k) str="$str filter_name_key@$parm";;
		l) str="$(list_block)";;
		f) rn="$rn render";;
		q) rn="$rn number_str";;
		e) rn="$rn log_out";;
		s) rn="$rn direct_render";;
		w) rn="$rn format_write";;
		z) limit=$parm;;
		*) error_pros 3;
	esac
done

if [ "$rn" == "" ]; then
	rn="direct_render"
fi

str="$str $rn"
handlers "$str"
(( nest++ ))
recursive_read $conf "$str"