#!/bin/bash

# Функция проверки пра и исполнения
exec_sh()
{
	declare -i timework

	timeout=$1
	shift

	file=$1
	shift

	name=$(echo $file | awk -F "/" '{print $NF}' )

	owner=$(ls -l $file | cut -d' ' -f3)
	su $owner -c "$file $(echo $@)" > /tmp/ubconfig/$name.txt &

	pid=$!

	timeout_run $timeout &

}

# Функция контроля времени исполнения
timeout_run()
{
	timework=1
	timeout=$1

	while [ $timeout -gt $timework -a "$(ps $pid | grep : )" != "" ]
	do
		timework=$(ps -p $pid -o etimes= | sed 's/ //g')

		if [ $timeout -eq $timework ]; then
			kill $pid
			echo "Prosses stopped !!" >> /tmp/ubconfig/$name.txt
		fi
	done
}

cd /tmp
i=0

if [ "$1" == "start" ]; then
	mkdir ubconfig
	touch ubconfig/turn

	while [ $i -ne 1 ]
	do
		str=$(cat ubconfig/turn | head -n 1 )

		if [ "$str" != "" ]; then
			sed -i '1d' ubconfig/turn 
			exec_sh $str
		fi

		sleep 1
	done

else
	rm -f -r ubconfig 
fi