#!/bin/bash

path_run=$(dirname $0)

. $path_run/action.sh

function sh_run
{
	while read line;
	do
		$line
		
	done < $1
}

while getopts "d:l:iv:" opt
do
	#parm=$(echo $OPTARG | sed 's/ /@/g')
	case $opt in
		d) del_block $OPTARG;;
		l) del_write $OPTARG;;
		i) echo "$str filter_type@$parm";;
		v) ins_write $OPTARG;;
		*) echo "Dick";
	esac
done

#del_write "Screen" 1 "Device" "test"
#del_block "InputDevice" 2 "test"
#ins_write "test" "ServerFlags" 1  "\ \ Key \"Value\""
#ins_block "test" "Sec" "MyBlock" 
#ins_write "MyBlock" 1 "test" "\ \ Device \"Out_Mouse\""
#ins_write "MyBlock" 1  "test" "\ \ Device \"Output_mouse\""
#ins_write MyBlock 1 test "Device Out_Keyboard"
#del_block "MyBlock" 1 "test"
#ins_write "Monitor" 1 "test" "\ \ Device \"Out_Mouse\""
#sh_run $path_run/test.txt
