#!/bin/bash

path_run=$(dirname $0)

. $path_run/action.sh


while getopts "d:l:i:v:u:" opt
do

	case $opt in
		d) del_block $OPTARG;;
		l) del_write $OPTARG;;
		i) ins_block $OPTARG;;
		v) ins_write $OPTARG;;
		u) update_write $OPTARG;;
		*) echo "Emtry key";
	esac
done
