#!/bin/bash

path_run=$(dirname $0)

. $path_run/action.sh


while getopts "d:l:i:v:" opt
do
	#parm=$(echo $OPTARG | sed 's/ /@/g')
	case $opt in
		d) del_block $OPTARG;;
		l) del_write $OPTARG;;
		i) ins_block $OPTARG;;
		v) 	str1=$(echo $OPTARG | cut -d' ' -f1)
		 	str2=$(echo $OPTARG | cut -d' ' -f2)
		 	str3=$(echo $OPTARG | cut -d' ' -f3)
		 	str4=$(echo $OPTARG | cut -d' ' --complement -f1,2,3)
			ins_write $str1 $str2 $str3 "$str4";;
		*) echo "Emtry key";
	esac
done

#del_write "Screen" 1 "Device" "test"
#del_block "InputDevice" 2 "test"
#ins_write "test" "ServerFlags" 1  "\ \ Key \"Value\""
#ins_block "test" "Sec" "MyBlock" 
#ins_write "MyBlock" 1 "test" "\ \ Device \"Out_Mouse\""
#ins_write "MyBlock" 1  "test" "\ \ Device \"Output_mouse\""
#ins_write MyBlock 1 test "Device Out_Keyboard"
#del_block "MyBlock" 1 "test"
#ins_write "Monitor" 1 "test" "\ \ Device \"Out_Mouse\""